### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/coreos-nvidia#6]
https://travis-ci.org/src-d/coreos-nvidia/jobs/372424195#L1821

**Comment by trevex** [comment]
If I run it locally it works fine, possibly just invalid credentials on their side currently.

**Comment by trevex** [comment]
It worked locally, because I skipped the `docker login`. After a closer look it looks like the password is not properly piped.

I fixed this in my [fork](https://github.com/trevex/coreos-nvidia). As a temporary workaround you can use [image](https://hub.docker.com/r/trevex/coreos-nvidia/) of the fork built [here](https://travis-ci.org/trevex/coreos-nvidia) (looks like alpha channel is broken though).

PR https://github.com/src-d/coreos-nvidia/pull/7

**Comment by vmarkovtsev** [comment]
@mcuadros @smola

**Comment by smola** [comment]
@vmarkovtsev It seems this is fixed now: https://travis-ci.org/src-d/coreos-nvidia/builds/388164486

**Comment by vmarkovtsev** [comment]
Thanks for the fix @trevex !
